/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto3;

import javax.swing.JOptionPane;


public class PantallaInicioFrame extends javax.swing.JFrame {
    
    ComoJugarFrame howToPlay = new ComoJugarFrame();
    TableroJuegoFrame tablero = new TableroJuegoFrame();
    
    public PantallaInicioFrame() {
        initComponents();
        this.setLocationRelativeTo(null);   //ASI SE PONE LA VENTANA CENTRADA


    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartGameButton = new javax.swing.JButton();
        HowToPlayButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        TitleLabel = new javax.swing.JLabel();
        BackGroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 603));
        setMinimumSize(new java.awt.Dimension(700, 603));
        setResizable(false);
        getContentPane().setLayout(null);

        StartGameButton.setBackground(new java.awt.Color(0, 153, 51));
        StartGameButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        StartGameButton.setForeground(new java.awt.Color(255, 255, 255));
        StartGameButton.setText("Comenzar Partida");
        StartGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(StartGameButton);
        StartGameButton.setBounds(240, 130, 170, 60);

        HowToPlayButton.setBackground(new java.awt.Color(51, 51, 255));
        HowToPlayButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        HowToPlayButton.setForeground(new java.awt.Color(255, 255, 255));
        HowToPlayButton.setText("¿Cómo Jugar?");
        HowToPlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HowToPlayButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HowToPlayButton);
        HowToPlayButton.setBounds(240, 220, 170, 60);

        ExitButton.setBackground(new java.awt.Color(204, 51, 0));
        ExitButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("Salir");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(270, 310, 110, 50);

        TitleLabel.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setText("OUTFOXED VERSION AMONG US");
        getContentPane().add(TitleLabel);
        TitleLabel.setBounds(160, 30, 420, 50);

        BackGroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto3/AmongUsFondo.jpg"))); // NOI18N
        getContentPane().add(BackGroundImageLabel);
        BackGroundImageLabel.setBounds(0, 0, 700, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HowToPlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HowToPlayButtonActionPerformed
        howToPlay.setVisible(true);
    }//GEN-LAST:event_HowToPlayButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void StartGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameButtonActionPerformed
        tablero.setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(rootPane,"Antes de empezar, revele 2 tripulantes cualesquiera.","",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_StartGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicioFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundImageLabel;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton HowToPlayButton;
    private javax.swing.JButton StartGameButton;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
}
